### ISSUE TITLE
[🐛BUG] 使用你们提供的diginetica_session序列推荐数据集用benchmark_filename方式引入运行出现CUDA错误

### ISSUE THREAD

**Issue by iicanfly** [RUCAIBox/RecBole#1357]
模型BERT4Rec或者SASRec，使用你们提供的diginetica_session数据集用benchmark_filename方式引入运行出现CUDA错误。使用GRU4Rec或TransRec模型，则能正常使用

yaml配置

# dataset config
seed: 42
USER_ID_FIELD: session_id
alias_of_item_id: [item_id_list]
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id
load_col:
    inter: [session_id, item_id_list, item_id]

benchmark_filename: ['train', 'valid', 'test']

# training and evaluation
epochs: 500
topk: [1,10,20,5000]
train_batch_size: 256
eval_batch_size: 100
valid_metric: mrr@10
eval_args:
  split: {'LS': 'valid_and_test'}
  order: TO
neg_sampling: ~
metrics: ['MRR', 'NDCG', 'Hit']`

运行文件
`from recbole.quick_start import run_recbole

run_recbole(model='SASRec', dataset='dig', config_file_list=['test2.yaml'])`

出现问题
`Trainable parameters: 2861568
Train     0:   0%|                                                         | 0/2811 [00:00<?, ?it/s]C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [33,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [34,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [35,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [36,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [37,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [38,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [39,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [40,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [41,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [42,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [43,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [44,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [45,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [46,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [47,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [48,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [49,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [50,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [51,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [52,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [53,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [54,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [55,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [56,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [57,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [58,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [59,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [60,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [61,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [62,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Indexing.cu:702: block: [58,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Train     0:   0%|                                                         | 0/2811 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "run2.py", line 3, in <module>
    run_recbole(model='SASRec', dataset='dig', config_file_list=['test2.yaml'])
  File "C:\ProgramData\Miniconda3\envs\py37cu111\lib\site-packages\recbole\quick_start\quick_start.py", line 57, in run_recbole
    train_data, valid_data, saved=saved, show_progress=config['show_progress']
  File "C:\ProgramData\Miniconda3\envs\py37cu111\lib\site-packages\recbole\trainer\trainer.py", line 335, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "C:\ProgramData\Miniconda3\envs\py37cu111\lib\site-packages\recbole\trainer\trainer.py", line 181, in _train_epoch
    losses = loss_func(interaction)
  File "C:\ProgramData\Miniconda3\envs\py37cu111\lib\site-packages\recbole\model\sequential_recommender\sasrec.py", line 111, in calculate_loss
    seq_output = self.forward(item_seq, item_seq_len)
  File "C:\ProgramData\Miniconda3\envs\py37cu111\lib\site-packages\recbole\model\sequential_recommender\sasrec.py", line 99, in forward
    input_emb = self.dropout(input_emb)
  File "C:\ProgramData\Miniconda3\envs\py37cu111\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\py37cu111\lib\site-packages\torch\nn\modules\dropout.py", line 58, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "C:\ProgramData\Miniconda3\envs\py37cu111\lib\site-packages\torch\nn\functional.py", line 1168, in dropout
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.`

实验环境：
 - 操作系统: win10
- RecBole 版本: 1.0.1
 - Python 版本: py3.7
- PyTorch 版本: 1.9.0
- cudatoolkit 版本: cuda11.1

**Comment by Sherry-XLL** [comment]
你好 @iicanfly，感谢对伯乐项目的关注！

我通过 [URL](https://recbole.s3-accelerate.amazonaws.com/ProcessedDatasets/DIGINETICA/merged/diginetica.zip) 下载了伯乐提供的 diginetica_session 序列推荐数据集，并使用如下配置文件，命名为 `diginetica_sequential.yaml`：

```
# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 20
POSITION_FIELD: position_id
load_col:
  inter: [session_id, item_id, timestamp]
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# training and evaluation
epochs: 500
train_batch_size: 4096
eval_batch_size: 2000
valid_metric: MRR@10
eval_args:
  split: {'LS':"valid_and_test"}
  mode: full
  order: TO
neg_sampling: ~

# model
embedding_size: 64 
```

使用命令行 `python run_recbole.py --model=SASRec --dataset=diginetica --config_files=diginetica_sequential.yaml` 运行 BERT4Rec 和 SASRec 模型一切正常。

benchmark 引入的方式可能本来没有问题，但在划分 train、valid、test 时可能没有遵循伯乐序列推荐的数据要求。对于你出现的报错，可能是在 benchmark 文件划分时出现了下标选择溢出的问题，你可以试着用非 benchmark 引入的方式运行代码；或者在引入时使用 CPU，即 `use_gpu: False` 来定位数组出错位置。

如果报错仍然存在，或者确实是代码方面的问题，欢迎随时与我们联系。

**Comment by iicanfly** [comment]
> 你好 @iicanfly，感谢对伯乐项目的关注！
> 
> 我通过 [URL](https://recbole.s3-accelerate.amazonaws.com/ProcessedDatasets/DIGINETICA/merged/diginetica.zip) 下载了伯乐提供的 diginetica_session 序列推荐数据集，并使用如下配置文件，命名为 `diginetica_sequential.yaml`：
> 
> ```
> # dataset config
> field_separator: "\t"
> seq_separator: " "
> USER_ID_FIELD: session_id
> ITEM_ID_FIELD: item_id
> TIME_FIELD: timestamp
> NEG_PREFIX: neg_
> ITEM_LIST_LENGTH_FIELD: item_length
> LIST_SUFFIX: _list
> MAX_ITEM_LIST_LENGTH: 20
> POSITION_FIELD: position_id
> load_col:
>   inter: [session_id, item_id, timestamp]
> user_inter_num_interval: "[5,inf)"
> item_inter_num_interval: "[5,inf)"
> 
> # training and evaluation
> epochs: 500
> train_batch_size: 4096
> eval_batch_size: 2000
> valid_metric: MRR@10
> eval_args:
>   split: {'LS':"valid_and_test"}
>   mode: full
>   order: TO
> neg_sampling: ~
> 
> # model
> embedding_size: 64 
> ```
> 
> 使用命令行 `python run_recbole.py --model=SASRec --dataset=diginetica --config_files=diginetica_sequential.yaml` 运行 BERT4Rec 和 SASRec 模型一切正常。
> 
> benchmark 引入的方式可能本来没有问题，但在划分 train、valid、test 时可能没有遵循伯乐序列推荐的数据要求。对于你出现的报错，可能是在 benchmark 文件划分时出现了下标选择溢出的问题，你可以试着用非 benchmark 引入的方式运行代码；或者在引入时使用 CPU，即 `use_gpu: False` 来定位数组出错位置。
> 
> 如果报错仍然存在，或者确实是代码方面的问题，欢迎随时与我们联系。

你好，我使用的数据集是你们在https://github.com/RUCAIBox/RecBole/issues/1069里提供的针对于benchmark方式的diginetica-session数据集，valid和test都是使用diginetica_session.test.inter文件，数据要求应该是符合的。原子格式的数据集能正常使用，麻烦你们查看一下benmark方式是否存在异常。

**Comment by Sherry-XLL** [comment]
@iicanfly 你好，跟 benchmark 的加载关系不大，主要是在生成 benchmark 数据集文件时设定的参数 `MAX_ITEM_LIST_LENGTH: 70`，因此在使用的时候也需要在配置文件中加入这一参数，否则 `item_id_list` 将会超过 `max_seq_length` 的长度，使得 `position_embedding` 溢出，造成 SASRec 和 BERT4Rec 的问题。

正确的配置文件如下所示：

```
# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 70
POSITION_FIELD: position_id
load_col: ~

# training and evaluation
epochs: 500
train_batch_size: 4096
eval_batch_size: 2000
valid_metric: MRR@10
eval_args:
  split: {'LS':"test_only"}
  mode: full
  order: TO
neg_sampling: ~
benchmark_filename: ['train', 'test']
alias_of_item_id: ['item_id_list']

# model
embedding_size: 64 
```

**Comment by iicanfly** [comment]
谢谢，已解决

**Comment by HoupingY** [comment]
是需要修改MAX_ITEM_LIST_LENGTH吗？
